#!/bin/bash
clear
export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
set -x

level=$1
if [ -z "$level" ]; then
  level=3
fi
echo "starting: $0 <LOG_LEVEL=$1>"

echo "sourcing init"
source init

#log.level 5


important.log "
now in $0
"

console.log   "can you see console.log"
important.log "can you see important.log"
warn.log      "can you see warn.log"

echo "switching log level back to 4"
log.level 6
this.isSourced

important.log "
now starting init
"
init
warn.log      "done with starting init"
