#!/usr/bin/env bash
#clear
#export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

### new.method

c2.usage()
{
  local this=${0##*/}
  echo "You started" 
  echo "$0

  Usage:
  $this: is the next generation completion with regards to function parameter and types"
  this.help
  echo "
      ----      --------------------------
  Examples
    $this v
    $This init
  "
}
c2.init() {
  info.log "c2 init"
}

c2.start()
{
  #echo "sourcing init"
  source this
  source line
  c2.init


  this.start "$@"
}

c2.start "$@"

