#!/bin/bash
#clear
#export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

config.v() {
  echo "$0 version 2021-10-19 15:25"
}

config.ci() {
  once.completion.install
  /var/dev/Workspaces/2cuGitHub/once.sh/oosh 
}

config.completion.install() 
{
  DIR=${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions
  once.path.create $DIR
  echo "
_oo_commands()
{
    #echo processing once completion
    local cur prev opts
    #local IFS=$'\\n'

    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    #opts=\$(grep \"^once\.\${cur}.*()\" once | sed 's/^\(once\.\)\(.*\)\(().*\)/\2/')
    opts=\$(once completion.discover \${cur} \${prev})
    #echo cool \${opts}

    COMPREPLY=( "\${opts}" )
    return 0
}
complete -F _oo_commands once  
  " >$DIR/_once_commands
  if [ ! -f ~/.bashrc.bak.without.completion ]; then
    cp ~/.bashrc ~/.bashrc.bak.without.completion 
  fi
  cp /var/dev/EAMD.ucp/Components/com/ceruleanCircle/EAM/1_infrastructure/NewUserStuff/scripts/templates/.bashrc ~/.bashrc
} 


config.init()
{
  export CONFIG=~/config/user.env
  echo $CONFIG
  if [ ! -d ~/config ]; then
    mkdir ~/config
    config.path
  #else
  #  source $CONFIG
  fi
}

config.usage()
{
  local this=${0##*/}
  echo "You started 
$0

  Usage:
  $this: command   description and Parameter
      v         print version information
      init      initializes a new user config  
  
  Examples
    $this v
    $this init
  "
  
  #loop.list PATH print '---------------------: '
}

config.start()
{
  #echo "sourcing init"
  source init

  this.start "$@"
}

config.start "$@"

