#!/usr/bin/env bash
#clear
#export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

createLink.user()     # <path> <?user1> <?user2>... # A symbolic link is created to the given users' home directory or all users' home directory of the given path+directory # an example
{
  local arg1="$1"
  if [ -n "$arg1" ]; then
    shift
    info.log "arg1 is set to $arg1"
  else
    create.result 1 "arg1 missing. Using: $arg1"
    exit "$(result)"
  fi

  if check dir "$arg1" not exists
  then
    create.result 1 "$arg1 does not exist"
    echo "$arg1 does not exist"
    exit "$(result)"
  fi

  local arg2="$1"
  if [ -n "$all" ]; then
    #local allUsers=$(c2 user.completion)
    local allUsers=$(getent passwd | awk -F: '$3>999 && $3 <5000{print $1}')
    allUsers+=' root'
    #allUsers=$(echo )
    echo $allUsers
    createLink users "$arg1" "$allUsers"
  else
    if [[ ${arg1::1} == "/" ]]; then
      arg1="${arg1/\/}"
    fi
    if [ -z "$arg2" ]; then 
      arg2="$(whoami)"
    fi

    while [ -n "$arg2"  ];
    do
      if check user $arg2 exists fix error.log "$arg2 is not a user"
      then
        info.log "arg2 is set to $arg2"
        
        if [ $(id -u "$(whoami)") -eq 0 ]; then
          if [ $(whoami) = "$arg2" ]; then
            echo "Admin: $(whoami)"
            if check dir $arg2 exists
            then
              ln -s "$arg1" "/$arg2/$arg1"
            else
              ln -s "$arg1" "/$arg1"
            fi
          else
            ln -s "$arg1" "/home/$arg2/$arg1"
          fi
          chmod -R 775 "/$arg1"
        else
          local targetDir="${arg1%\/*}"
          mkdir -p "$targetDir"
          sudo ln -s "/$arg1" --target-directory="/home/$arg2/$targetDir"
          sudo chmod -R 775 "/$arg1"
        fi
        create.result 0 "arg1 is link to $arg2"
      fi
      shift
      arg2="$1"
    done
  fi

  return $(result)
}

createLink.for() { # <mode:user> # createLink for either specific users or all users
  debug.log "for"
  RETURN=$1
}

#createLink.for.completion() { 
#  echo "all"
#  echo "user"
#}

createLink.for.completion.mode() { # #
  echo "all"
  echo "user"
}

createLink.all() { # #
  all=true
  RETURN=$1
}

### new.method

createLink.usage()
{
  local this=${0##*/}
  echo "You started" 
  echo "$0

  Usage:
  $this: command   Parameter and Description"
  this.help
  echo "
  
  Examples
    $this v
    $this init
    $this for users /var/dev snet shiftAdmin
    $this for all users /var/dev
    ----------
  "
}

createLink.start()
{
  #echo "sourcing init"
  source this

  # if [ -z "$1" ]; then
  #   status.discover "$@"
  #   return 0
  # fi

  this.start "$@"
}

createLink.start "$@"

