#!/usr/bin/env bash
#clear
#export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

currentUser.basicInfo()     # <nickname> <name> <birthday> <role> # Asking for the basic info of the current user to print to a file # an example
{
 local arg1="$1"
 if [ -n "$arg1" ]; then
   shift
   create.result 0 "arg1 is set to $arg1"
 else
  arg1=defualtVlaue
  create.result 1 "arg1 missing. Using: $arg1"
 fi
 info.log "arg1 is set to $arg1"


 return $(result)
}

### new.method

currentUser.usage()
{
  local this=${0##*/}
  echo "You started" 
  echo "$0

  Usage:
  $this: command   Parameter and Description"
  this.help
  echo "
  
  Examples
    $this v
    $this init
    $this basicInfo “Billy” “Bob Bill” “12-31-1999” “admin”
    ----------
  "
}

currentUser.start()
{
  #echo "sourcing init"
  source this

  # if [ -z "$1" ]; then
  #   status.discover "$@"
  #   return 0
  # fi

  this.start "$@"
}

currentUser.start "$@"

