#!/usr/bin/env bash
#clear
#export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

### new.method

disk.usage() {
  # <<EOD
  local this=${0##*/}
  echo "You started"
  echo "$0

  Usage:
  $this: command   description and Parameter

      usage     prints this dialog while it will print the status when there are no parameters
      v         print version information
      init      initializes ...nothing yet

      space.usage     lists and sums used disk space for number of <levels>
      space.free      show free space on the mounted volumes

  Examples
    $this v
    $this init

    $this image disk1
  "
}

disk.space.used() { # <?depthLevel:2> # calculates the space used in this directory
  # use "disk list.result.bySize" to see a sorted barchart
  # <<EOD
  local level="$1"
  shift
  if [ -z "$level" ]; then
    level=2
  fi
  if ! this.isNumber $level; then
    warn.log "level is not a number: $level"
    level=2
    silent.log "fixing level to 2"
  fi
  capture.log du -chd $level
  RETURN="$1"
}

disk.space.free() { # # lists the free space on the mounted filesystems
  # <<EOD
  df -h
}

disk.find() { # <?findArguments> # finds files in the subdirectories here matching <findArguments>
  # <<EOD
  find . "$*"
}

disk.find.completion.pattern() {
  # <<EOD
  echo -e "'-type f'\\n'-type d'\\n'-name '"
}

disk.find.dir() { # <?name> # finds directories in the subdirectories here matching <name>
  # <<EOD
  find . -type d -name "$1"
}

disk.find.file() { # <?name> # finds files in the subdirectories here matching <name>
  # <<EOD
  find . -type f -name "$1"
}

disk.list.result.bySize() { #  # prints the last disk space.used calculation as bar chart
  # <<EOD
  #cat $CONFIG_PATH/result.txt | sort -hr | awk '{printf "%-10s %40s %.*s\n",$1,$2,$1,"▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄"}'
  cat $CONFIG_PATH/result.txt | sort -hr | awk '{printf "%-10s %40s %.*s\n",$1,$2,$1,"◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼"}'
}

disk.list.result() { #  # prints the last disk space.used calculation
  # <<EOD
  cat $CONFIG_PATH/result.txt
}

disk.calc() { # <mathExpression> # calculates the expression
  # <<EOD
  echo $(($*))
}

disk.calc.getBytesInTB() { # <number> # calculates the <number> of TerraBites in bytes
  # <<EOD
  echo $(($1 * 1024 * 1024 * 1024 * 1024))
}

disk.calc.getBytesInGB() { # <number> # calculates the <number> of GigaBites in bytes
  # <<EOD
  echo $(($1 * 1024 * 1024 * 1024))
}

disk.calc.getBytesInMB() { # <number> # calculates the <number> of MegaBites in bytes
  # <<EOD
  echo $(($1 * 1024 * 1024))
}

disk.calc.getBytesInKB() { # <number> # calculates the <number> of MegaBites in bytes
  # <<EOD
  echo $(($1 * 1024))
}

disk.calc.getTB() { # <number> # calculates the <number> of bytes into TerraBites
  # <<EOD
  echo "$(($1 / 1024 / 1024 / 1024 / 1024)) TB"
}

disk.calc.getGB() { # <number> # calculates the <number> of bytes into GigaBites
  # <<EOD
  echo "$(($1 / 1024 / 1024 / 1024)) GB"
}

disk.calc.getMB() { # <number> # calculates the <number> of bytes into MegaBites
  # <<EOD
  echo "$(($1 / 1024 / 1024)) MB"
}

disk.calc.getKB() { # <number> # calculates the <number> of bytes into KiloBites
  # <<EOD
  echo "$(($1 / 1024)) KB"
}

disk.list() { #  # os independant listing of attached disks
  # <<EOD
  if os.check disk.list; then
    $RESULT "$@"
  else
    important.log "$RESULT is not supported"
  fi
}

disk.list.darwin() { #  # darwin OS listing of attached disks
  # <<EOD
  diskutil list
}

disk.list.linux() { #  # linux OS listing of attached disks
  # <<EOD
  $SUDO lsblk -e7
}

disk.list.byUUID() { #  # darwin OS listing of attached disks
  # <<EOD
  $SUDO ls -lha /dev/disk/by-uuid/
}

disk.list.by() { # <listOption> # darwin OS listing of attached disks
  # <<EOD
  $SUDO ls -lha /dev/disk/by-$1
}

disk.parameter.completion.listOption() { # #
  # <<EOD
  c2 folders.completion /dev/disk/ | line replace "\/dev\/disk\/by-"
}

disk.eject() { #  # OS independant unmount of disks
  # <<EOD
  if os.check disk.eject; then
    $RESULT "$@"
  else
    important.log "$RESULT is not supported"
  fi
}

disk.get() { #  # os independant listing of attached disks
  # <<EOD
  if os.check disk.get; then
    $RESULT "$@"
  else
    important.log "$RESULT is not supported"
  fi
}

disk.get.linux() { # #
  # <<EOD
  local disk="$1"
  if [ -n "$1" ]; then
    shift
  fi
  blkid \
    | line split " " \
    | line replace.sedquoted '/dev' '--- DEVICE=/dev' \
    | line split '--- ' #\
  #| line find "$disk" "^$"
}

disk.name2device() { # # if first parameter is empty it reads fro  std input and converts the name into a device path
  # <<EOD
  local name="$1"
  if [ -n "$1" ]; then
    shift
  else
    name=$(cat -)
  fi
  echo "$name" \
    | line replace.sedquoted "-" "/" \
    | line replace.sedquoted "^" "/dev/"
}

disk.discover() { #  # os independant listing of attached disks
  # <<EOD
  if os.check disk.discover; then
    $RESULT "$@"
  else
    important.log "$RESULT is not supported"
  fi
}

disk.discover.linux() { # #
  # <<EOD
  local disk="$1"
  if [ -n "$1" ]; then
    shift
  fi
  # blkid \
  # | line split " " \
  # | line replace.sedquoted '/dev' '--- DEVICE=/dev' \
  # | line split '--- '

  lsblk --noheadings -o NAME,MOUNTPOINT \
    | line find "^[ ]*└[^ ]* $" \
    | line replace "[ ]*└─"
}

disk.automount() { # #
  # <<EOD
  disk.discover \
    | xargs disk.name2device \
    | xargs udisksctl mount -b
}

disk.automount.create.config() { # #
  # <<EOD
  {
    echo "[Unit]"
    echo "Description=Automounted $device"
    echo ""
    echo "[Mount]"
    echo "What=$device"
    echo "Where=/media/pi/"
    echo "Type=ext4"
    echo "Options=defaults"
    echo ""
    echo "[Install]"
    echo "WantedBy=multi-user.target"
  } > /etc/systemd/system/media-pi-$UUID.mount
}

disk.eject.darwin() {
  # <<EOD
  local disk="$1"
  if [ -n "$1" ]; then
    shift
  fi

  if [ -n "$disk" ]; then
    diskutil unmountDisk /dev/$disk
  else
    private.disk.args.error.disk
  fi
}

private.disk.args.error.disk() {
  # <<EOD
  error.log "no disk specified."
  disk.list
  important.log "just specify the disk name: if /dev/disk1 is listed do: disk eject disk1"
}

disk.image() { # <disk> <imageFile:./$disk.img.gz>  # create a disk image with progress bar
  # <<EOD
  if os.check disk.image; then
    $RESULT "$@"
  else
    important.log "$RESULT is not supported"
  fi
}

disk.image.darwin() {
  # <<EOD
  disk.image.linux "$@"
}

disk.image.linux() {
  # <<EOD
  local disk="$1"
  if [ -n "$1" ]; then
    shift
  else
    private.disk.args.error.disk
    return 2
  fi
  local imageFile="$1"
  if [ -n "$1" ]; then
    shift
  else
    imageFile="./$disk.img.gz"
  fi

  # if [ "$user" = "root" ]; then
  #   SUDO=""
  # else
  #   SUDO="sudo "
  # fi

  #$SUDO dd if="/disk/r${disk}" bs=1m status=progress | gzip >$imageFile
  $SUDO pv -tpreb "/dev/r${disk}" | dd bs=128m | gzip > $imageFile

  #sudo echo "starting"
  #($SUDO pv -n "/dev/r${disk}" | dd of="$imageFile" bs=128M conv=notrunc,noerror) 2>&1 | dialog --gauge "Cloning disk /dev/r${disk} to , please wait..." 10 70 0
}

disk.restore.linux() { # <disk> <imageFile:./$disk.img.gz>  # restore a disk imageFile with progress bar
  # <<EOD
  local disk="$1"
  if [ -n "$1" ]; then
    shift
  else
    private.disk.args.error.disk
    return 2
  fi

  local imageFile="$1"
  if [ -n "$1" ]; then
    shift
  else
    imageFile="./$disk.img.gz"
  fi

  # if [ "$user" = "root" ]; then
  #   SUDO=""
  # else
  #   SUDO="sudo "
  # fi

  disk.eject ${disk}
  sudo echo "starting..."
  #$SUDO dd if="/disk/r${disk}" bs=1m status=progress | gzip >$imageFile
  $SUDO pv -tpreb "$imageFile" | gzip -dc | $SUDO dd of=/dev/r${disk} bs=128m conv=notrunc,noerror

  #($SUDO pv -n "/dev/r${disk}" | dd of="$imageFile" bs=128M conv=notrunc,noerror) 2>&1 | dialog --gauge "Cloning disk /dev/r${disk} to , please wait..." 10 70 0
}

disk.install.raid.support() { # # install all the necessary packeges for managing RAID and Virtual Partitions
  # <<EOD
  oo cmd mdadm
  oo cmd lvm2
  important.log "Please Reboot before you continue...."
}

disk.install.samba.support() { # # install all the necessary packeges for managing RAID and Virtual Partitions
  # <<EOD
  install samba.support
}

disk.start() { # <method> <parameter> # default start and parameter processing
  # <<EOD
  #echo "sourcing init"
  source this
  source os

  # if [ -z "$1" ]; then
  #   status.discover "$@"
  #   return 0
  # fi

  this.start "$@"
}

disk.start "$@"
