#!/usr/local/bin/bash
#clear
#export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

this=${0##*/}
if [ "$this" = "fix" ]; then
  echo "$this was started. please use 
  . fix
  
  "
  exit 0
fi

if [ -z "$EXPECTED_RETURN_VALUE" ]; then
  export EXPECTED_RETURN_VALUE=7
fi

if [ -z "$ERROR_CODE_RECONFIG" ]; then
  export ERROR_CODE_RECONFIG=7
fi
exit $ERROR_CODE_RECONFIG