#!/usr/local/bin/bash
#clear
#export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"


while [ -n "$1" ]
  do
  echo fix: $1
    case "$1" in
      "cd")
        shift
        echo "writing: $CONFIG_PATH/reconfigure"
        echo "OOSH_STARTDIR=""$1" >>$CONFIG_PATH/reconfigure
      ;;
      "list")
        shift
        cat $CONFIG_PATH/reconfigure
      ;;
      "write")
        shift
        echo "$1" >>$CONFIG_PATH/reconfigure
        ;;
      "delete")
        shift
        rm $CONFIG_PATH/reconfigure
      ;;
      *)
        echo "fix: unknown options: $*"
      ;;
    esac
    shift
    
  done

this=${0##*/}
if [ "$this" = "fix" ]; then
  echo "$this was started. please use 
  . fix
  
  "
  exit $ERROR_CODE_RECONFIG
fi


if [ -z "$EXPECTED_RETURN_VALUE" ]; then
  export EXPECTED_RETURN_VALUE=7
fi

if [ -z "$ERROR_CODE_RECONFIG" ]; then
  export ERROR_CODE_RECONFIG=7
fi
exit $ERROR_CODE_RECONFIG