#!/usr/bin/env bash
#clear
#export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

hannesn.read()      # help text
{
 local arg1="$1"
 if [ -n "$arg1" ]; then
   shift
   create.result 0 "arg1 is set to $arg1"
 else
  arg1=defualtVlaue
  create.result 1 "arg1 missing. Using: $arg1"
 fi
 info.log "arg1 is set to $arg1"


 return $(result)
}

### new.method

hannesn.usage()
{
  local this=${0##*/}
  echo "You started 
$0

  Usage:
  $this: command   description and Parameter

      usage     prints this dialog while it will print the status when tehere are no parameters          
      v         print version information
      init      initializes ...nothing yet
      read      asdfghjjkk
      ----      --------------------------
  
  Examples
    $this v
    $this init
  "
}

hannesn.start()
{
  #echo "sourcing init"
  source this

  # if [ -z "$1" ]; then
  #   status.discover "$@"
  #   return 0
  # fi

  this.start "$@"
}

hannesn.start "$@"

