#!/usr/bin/env bash
#clear
#export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

### new.method

myId.create() # <sshConfigName> # lists the ids you have on this user
{
  echo create
  create.result 0 "That myID create worked well"
  export RESULT
}


myId.list() # <?id> # lists the ids you have on this user
{
  tree -L 1 ~/.ssh/ids
}

myId.noop() #  # just a test TDODO to be removed
{
  important.log "myId.noop went well"
}


myId.parameter.completion.id() {
  ls ~/.ssh/ids
}

myId.usage()
{
  local this=${0##*/}
  echo "You started" 
  echo "$0

  Usage:
  $this: command   Parameter and Description"
  this.help
  echo "
  
  Examples
    $this v
    $this init
    ----------
  "
}

myId.start()
{
  #echo "sourcing init"
  source this

  # if [ -z "$1" ]; then
  #   status.discover "$@"
  #   return 0
  # fi

  this.start "$@"
}

myId.start "$@"

