#!/usr/bin/env bash
#clear
#export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

### new.method

share.status() { # # shows th status of the sharing
  share.samba.status
}

share.samba.status() { # # shows th status of the sharing
  smbstatus
}

share.samba.service() { # <serviceCmd> # shows th status of the sharing
  local serviceCmd="$1"
  if [ -n "$1" ]; then
    shift
  else
    error.log "no serviceCmd specified"
    return 1
  fi  
  systemctl "$serviceCmd" smbd
}

share.parameter.completion.serviceCmd() {
  echo -e "enable \\nstatus \\nrestart \\nstop "
}

share.samba.config.edit() {  # # edit samba config
  edit /etc/samba/smb.conf
  share.samba.service restart
}

share.samba.restart() # #
{
  systemctl restart smbd
  systemctl restart avahi-daemon
  systemctl restart netatalk
}


share.samba.install() { # # install all the necessary packeges for managing RAID and Virtual Partitions
  important.log "Needs to be run as ROOT"
  oo cmd samba 
  oo cmd samba-common-bin
  oo cmd smbclient

  oo cmd netatalk

  important.log "Please set a samba password..."
  smbpasswd -a

  systemctl restart smbd

  #vim /etc/samba/smb.conf
    # [pishare]
    # path = /media/pi/shared
    # writeable=Yes
    # create mask=0777
    # directory mask=0777
    # public=no

  #vim /etc/nsswitch.conf
  #vim /etc/avahi/services/rfb.service
      # <?xml version="1.0" standalone='no'?>
      # <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
      # <service-group>
      #   <name replace-wildcards="yes">%h</name>
      #   <service>
      #     <type>_rfb._tcp</type>
      #     <port>5900</port>
      #   </service>
      # </service-group>  

  #vim /etc/avahi/services/smb.service
      # <?xml version="1.0" standalone='no'?>
      # <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
      # <service-group>
      #   <name replace-wildcards="yes">%h</name>
      #   <service>
      #     <type>_smb._tcp</type>
      #     <port>445</port>
      #   </service>
      #   <service>
      #     <type>_device-info._tcp</type>
      #     <port>0</port>
      #     <txt-record>model=Xserve</txt-record>
      #   </service>
      # </service-group>

  ## xxx service avahi-daemon start
  ## xxx service netatalk start
  systemctl enable avahi-daemon
  systemctl enable netatalk

  systemctl restart smbd
  systemctl restart avahi-daemon
  systemctl restart netatalk

  important.log "Please Reboot before you continue...."
}

share.usage()
{
  local this=${0##*/}
  echo "You started" 
  echo "$0

  Usage:
  $this: command   Parameter and Description"
  this.help
  echo "
  
  Examples
    $this v
    $this init
    ----------
  "
}

share.start()
{
  #echo "sourcing init"
  source this

  # if [ -z "$1" ]; then
  #   status.discover "$@"
  #   return 0
  # fi

  this.start "$@"
}

share.start "$@"

