#!/usr/bin/env bash
#clear
#export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

### new.method

private.states.init() # # initialises the stateMachine folder in $CONFIG_PATH 
{
  check dir $CONFIG_PATH/stateMachines not exists \
    call mkdir -p $CONFIG_PATH/stateMachines 
}

state.of() # <machine> <?method> # returns the state of the <machine>
{
  local machine=$1
  local stateID=${machine}_STATE_ID
  shift

  source $CONFIG_PATH/stateMachines/${machine}.states.env
  local state=${!stateID}
  local stateName="${machine}_STATES[${state}]"

  important.log "machine ${YELLOW}$machine ${CYAN}state is: ${WHITE}${!stateName}"
  STATE_MACHINE_CURRENT=$machine

  if [ -n "$1" ]; then 
    local call=$1
    shift
    state.$call - "$@"
  else
    echo ${state}
  fi
  RETURN=$1
}


state.name() # <machine> #
{
  local machine=$1
  if ! [ "$1" = "-" ]; then 
    state.of $machine name
    return 0
  fi
  echo ${!stateName}
}

state.id() # #
{
    local machine=$1
  if ! [ "$1" = "-" ]; then 
    state.of $machine id
    return 0
  fi
  echo ${state}
}

state.parameter.completion.machine() {
  state.list.machines $1
}

state.parameter.completion.nameFilter() {
  state.list.machines $1
}

state.list.machines() # <?nameFilter> # lists all available stateMachines
{
  cd $CONFIG_PATH/stateMachines
  c2 files.completion $1 | line replace ".states.env"

  if [ -n "$1" ]; then shift; fi
  RETURN=$1
}

state.machine.create() # <machine> # creates a stateMachine
{
  local machine=$1
  check file $CONFIG_PATH/stateMachines/${machine}.states.env not exists \
    call state machine.init $machine
}

state.machine.init() {
  local machine=$1
  declare -xag ${machine}_STATES='(\
    [0]="not.installed" \
    [1]="initialized" \
    [2]="setup" \
    [3]="all.states.added" \
    [4]="started" \
    [5]="finished" \
    [6]="to.be.deleted" \
    [7]=11 \
    [11]="custom1" \
    [12]=99 \
    [99]=5
    )' 
  
  declare -x ${machine}_STATE_ID=1 >>$CONFIG_PATH/stateMachines/${machine}.states.env
  {
    declare -a | line find ${machine}_STATES | line replace ' \[' ' \\-SPLIT-[' | line split '-SPLIT-' | line unquote
    local name=${machine}_STATE_ID
    echo ${name}=${!name}
  }>$CONFIG_PATH/stateMachines/${machine}.states.env
  
}

state.usage()
{
  local this=${0##*/}
  echo "You started" 
  echo "$0

  state allows you to create and handle multiple state machines

  Usage:
  $this: command   Parameter and Description"
  this.help
  echo "
  
  Examples
    $this list
    $this init
    ----------
  "
}

state.start()
{
  #echo "sourcing init"
  source this
  private.states.init

  # if [ -z "$1" ]; then
  #   status.discover "$@"
  #   return 0
  # fi

  this.start "$@"
}

state.start "$@"

