#!/bin/bash
clear

echo "t4 starting: $current"

declare -p
echo "==================="
function cool.scope() 
{
  local variable_local="local variable"
  echo "in t4.cool.scope: variable_local=$variable_local"
  echo "in t4.cool.scope: current=$current"
}


current="current $0"

cool.scope
echo "in t4.main: variable_local=$variable_local"
echo "in t4.main: current=$current"

echo "==================="
#current="t5 sub t4"

#good
#t5

#trouble
source t5

echo "in t4.main after t5"
echo "in t4.main: current=$current"
