#!/usr/local/bin/bash
#clear
#export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"



user.id()
{
  id
}

user.ssh.status()
{
  if [ -d ˜/.ssh ]; then
    create.result 0 "ssh initialized for $USER" "$1"
    return "$(result)"
  else
    create.result 1 "ssh does not exist for $USER" "$1"
    return "$(result)"
  fi
}

user.usage()
{
  local this=${0##*/}
  echo "You started 
$0

  Usage:
  $this: command   description and Parameter

      usage     prints this dialog while it will print the status when tehere are no parameters          
      v         print version information
      init      initializes a new user config  
  
  Examples
    $this v
    $this init
  "
}


user.start()
{
  #echo "sourcing init"
  source init

  # if [ -z "$1" ]; then
  #   status.discover "$@"
  #   return 0
  # fi

  this.start "$@"
}

user.start "$@"

