#!/bin/bash

# echo "entering: ${BASH_SOURCE[0]}"
# echo "remove all echos to preseve output"
# echo ""

source /var/dev/Workspaces/2cuGitHub/once.sh/v2/debug

this.isSourced()
{
  len=${#BASH_LINENO[@]}
  depth=1

  info.log "Functions: ${FUNCNAME[@]}"
  info.log "bash source: ${BASH_SOURCE[@]}"
  info.log len=$len, depth=$depth
  info.log "check: ${FUNCNAME[1]}"

  if [ "${FUNCNAME[1]}" = "main" ]; then
    info.log "mode starting ${FUNCNAME[@]} in ${BASH_SOURCE[0]##*/} from ${BASH_SOURCE[$len-1]##*/}"
    return 0
  else
    info.log "mode sourcing ${BASH_SOURCE[0]##*/} from ${BASH_SOURCE[$len-1]##*/}" 
    return 1
  fi
}

info.log "
still in ${BASH_SOURCE[0]##*/}
"

if (this.isSourced); then
 important.log "init was sourced"
else
 important.log "init was started"
fi