#!/usr/bin/env bash
#clear
#export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

### new.method

install.headless() # # installs all everything needed for headless operation
{
  ossh status
  sh -c "$(wget -O- https://gist.githubusercontent.com/vietanhdev/c2cb96eb6cf5b9232a04dfbe8bdaba2f/raw/164c8f9f7eccbcacaa44b14ddb4225d283e6a3c7/install_realvnc_server.sh)"

  # on pixel i used tigervnc

}

install.staus.headless() {
  systemctl status vncserver-virtuald.service
  systemctl status vncserver-x11-serviced.service
}

install.headless.enable() {
  systemctl start vncserver-virtuald.service
  systemctl start vncserver-x11-serviced.servicep
  systemctl enable vncserver-virtuald.service
  systemctl enable vncserver-x11-serviced.service
}

install.pacstall() {
  bash -c "$(wget -q https://git.io/JsADh -O -)"
}

install.snapAppStore() # # installs all everything needed for headless operation
{
  oo cmd snapd
  snap install snap-store

}

install.chromium() # # installs all everything needed for headless operation
{
  oo cmd chromium-browser
}



install.usage()
{
  local this=${0##*/}
  echo "You started" 
  echo "$0

  Usage:
  $this: command   Parameter and Description"
  this.help
  echo "
  
  Examples
    $this v
    $this init
    ----------
  "
}

install.start()
{
  #echo "sourcing init"
  source this

  # if [ -z "$1" ]; then
  #   status.discover "$@"
  #   return 0
  # fi

  this.start "$@"
}

install.start "$@"

