#!/usr/bin/env bash
#clear
#export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'
#set -x

#echo "starting: $0 <LOG_LEVEL=$1>"

### new.method

setup.headless() # # installs all everything needed for headless operation
{
  ossh status
  sh -c "$(wget -O- https://gist.githubusercontent.com/vietanhdev/c2cb96eb6cf5b9232a04dfbe8bdaba2f/raw/164c8f9f7eccbcacaa44b14ddb4225d283e6a3c7/install_realvnc_server.sh)"

  # on pixel i used tigervnc

}

setup.staus.headless() {
  systemctl status vncserver-virtuald.service
  systemctl status vncserver-x11-serviced.service
}

setup.headless.enable() {
  systemctl start vncserver-virtuald.service
  systemctl start vncserver-x11-serviced.servicep
  systemctl enable vncserver-virtuald.service
  systemctl enable vncserver-x11-serviced.service
}

setup.pacstall() {
  bash -c "$(wget -q https://git.io/JsADh -O -)"
}

setup.snapAppStore() # # installs all everything needed for headless operation
{
  oo cmd snapd
  snap install snap-store

}

setup.chromium() # # installs all everything needed for headless operation
{
  oo cmd chromium-browser
}


setup.docker() # #
{
  if os.check setup.docker; then
    $RESULT "$@"
  else
    important.log "$RESULT is not supported"
  fi  
}

setup.docker.linux() # #
{
        if [ -x "$(command -v apk)" ]; then
            apk update
            apk add docker
            addgroup $USERNAME docker            
            rc-update add docker boot
            service docker start
            apk add docker-compose
        elif [ -x "$(command -v apt-get)" ]; then
            echo "Installing Docker & Docker Compose..."
            apt-get update
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -y docker docker-compose
            # apt-get -y install curl apt-transport-https ca-certificates curl gnupg2 software-properties-common
            # curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
            # add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
            # apt-get update
            # apt-get -y install docker-ce docker-ce-cli containerd.io
            echo usermod -aG docker $USERNAME
            usermod -aG docker $USERNAME
            # curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            # chmod +x /usr/local/bin/docker-compose
            docker --version
            docker-compose --version
        elif [ -x "$(command -v pacman)" ]; then
            echo "Installing Docker & Docker Compose..."
            pacman -Syu
            echo "installing Docker......"
            pacman -S --needed docker
            echo "installing Docker Compose......"
            pacman -S --needed docker-compose
            groupadd docker
            gpasswd -a ${USERNAME} docker
        else
            message "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $1";
        fi
}
setup.docker.darwin() # #
{
  brew cask install docker
  brew install docker-compose
}

setup.npm() # # installs nvm and then the latest version of node.js
{
  oo cmd curl
  curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  nvm install node
}

setup.usage()
{
  local this=${0##*/}
  echo "You started" 
  echo "$0

  Usage:
  $this: command   Parameter and Description"
  this.help
  echo "
  
  Examples
    $this v
    $this init
    ----------
  "
}

setup.start()
{

  #echo "sourcing init"
  source this

  if [ ! "$USER" = "root" ]; then
    error.log "This state can only be executed by root"

    return 2
  fi

  # if [ -z "$1" ]; then
  #   status.discover "$@"
  #   return 0
  # fi

  this.start "$@"
}

setup.start "$@"

