#!/usr/bin/env bash
#set -x
#export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'

config.start() {
  # <<EOD
  This=$(which $0)
  this=$(basename $This)
  basepath=$(dirname $(readlink -f $This))
  source $basepath/init

  if [ "$this" = "config" ]; then
    #echo "starting $0"
    case $CONFIG in
      '')
        config.init
        source call "$@"
        ;;
      *)
        source "$CONFIG"
        source call "$@"

        if [ -z "$1" ]; then
          #config.env
          #echo "$CONFIG"
          config.file
        fi
        ;;
    esac
  else
    #echo "sourcing $0"
    config.init
  fi

}

config.start1() {
  # <<EOD
  This=$(which $0)
  this=$(basename $This)
  basepath=$(dirname $This)
}

config.init() {
  # <<EOD
  export CONFIG=~/config/user.env
  echo $CONFIG
  if [ ! -d ~/config ]; then
    mkdir ~/config
    config.path
  #else
  #  source $CONFIG
  fi
}

config.path() {
  # <<EOD
  PATH=$(dirname $(readlink -f $0)):$PATH
  config.save
}

config.save() {
  # <<EOD
  env | sed 's/\([^=]*\)=\(.*\)/export \1="\2"/' | grep -v "^export _" | grep -v "export PS" | grep -v "export BASH" | sort > $CONFIG
  #declare -a >>$CONFIG
}

config.file() {
  # <<EOD
  #user.log "$CONFIG"
  if [ -n "$1" ]; then
    export CONFIG="$1"
    config.save
  fi
  echo -e "\e[1;96m$CONFIG\e[0m"
}

config.edit() {
  # <<EOD
  vim config
}

config.env() {
  # <<EOD
  vim $CONFIG
}

config.list() {
  # <<EOD
  cat $CONFIG
}

config.get() {
  # <<EOD
  cat $CONFIG | grep $1
  shift
}

config.start $@
