#!/usr/bin/env bash

clear
export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'
set -x

t3.cool() {
  echo "t3.cool"
}


#echo "t3 starting"
#source t2

echo "workin in: $DIR"
source call t3.cool

echo check $(this.functionExists console.log)
if  (this.functionExists console.log) ; then
  echo yes
fi
echo "? $?"


kaputt

source call "$@"
