#!/usr/bin/env bash

echo "t5 starting: $current"

declare -p
echo "==================="
function cool.scope() {
  local variable_local="local variable"
  echo "in t5.cool.scope: variable_local=$variable_local"
  echo "in t5.cool.scope: current=$current"
}

current="current $0"

cool.scope
echo "in t5.main: variable_local=$variable_local"
echo "in t5.main: current=$current"

current=t5
echo "in t5.main: changed current=$current"
echo "t5 done   ==================="
