#!/usr/bin/env bash
clear
#export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'
#set -x

echo "$0 starting: $current"

t6.start() {
  source call "$@"
  #log warn "hallo"
  # local localLevel=3

  # if [ "$localLevel" -gt "2" ]; then
  #   echo cool localLevel: $localLevel
  # else
  #   echo bad  localLevel: $localLevel
  # fi

  echo "done"
}

t6.test() {
  success.log "${FUNCNAME[0]}"
  source log level 5
  RETURN=$1
}

t6.the() {
  success.log "${FUNCNAME[0]}"
  shift
  shift
  RETURN=$1
}

t6.start "$@"
