@startuml
actor Actor as a
participant sh
participant "init/oosh" as oosh 
participant "init/deinstall.oosh" as deinstall.oosh 
participant ossh
participant oo
participant bash
participant this

group Installation from GitHub
    alt curl
    else wget
        a -> sh: env -i sh -c "$(wget -O- https://raw.githubusercontent.com/Cerulean-Circle-GmbH/once.sh/main/init/oosh)"
    else fetch
    end
end
group Local Installation
    a -> oosh: init/oosh
    oosh -> sh: #!/bin/sh ### shebang
    sh -> bash: bash this localInstall
    bash -> this: this localInstall
    this -> bash: #!/usr/bin/env bash ### shebang
    this -> oo: oo state # initializes the state machine
    this -> user: user get home \n # hack to make sure the pm is set
    this -> bash: starts new bash
    bash -> bash: source .bashrc \n [oosh sshConfig] has started > |
end
group Remote Installation

    a -> ossh: ossh install <remoteSSHconfig> 

    ossh -> ossh: private.push.oosh
    ossh -> oosh: init/oosh mode ssh <remoteSSHconfig> <localSSHconfig> <localOSSH_MODE>
    ossh -> ossh: ossh.install.finish.local <remoteSSHconfig>
end
group Local De-Installation
    a -> deinstall.oosh: init/deinstall.oosh
end
@enduml