@startuml
  log -> log: log.level:243   - log log log type -t this.isSourced
  log -> log: log.level:243   - log log log '[' function = function ']'
  log -> log: log.level:244   - log log log this.isSourced
  this -> log: this.isSourced:485   - this log log log caller=log
  this -> log: this.isSourced:486   - this log log log callerFunction=log.level
  this -> log: this.isSourced:488   - this log log log case $callerFunction in
  this -> log: this.isSourced:503   - this log log log '[' log = log ']'
  this -> log: this.isSourced:504   - this log log log create.result 1 'started because log is /Users/marcel/oosh/log'
  this -> this: create.result:167   - this this log log log RETURN_VALUE=1
  this -> this: create.result:168   - this this log log log shift
  this -> this: create.result:169   - this this log log log RESULT='started because log is /Users/marcel/oosh/log'
  this -> this: create.result:170   - this this log log log shift
  this -> this: create.result:171   - this this log log log RETURN=
  this -> this: create.result:174   - this this log log log this.isNumber 1
  this -> this: this.isNumber:40   - this this this log log log case $1 in
  this -> this: this.isNumber:42   - this this this log log log return 0
  this -> this: create.result:179   - this this log log log info.log 'create.result: 1 started because log is /Users/marcel/oosh/log'
  this -> this: info.log:34   - this this this log log log '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this this log log log echo -e '\e[90mINFO-: create.result: 1 started because log is /Users/marcel/oosh/log\e[0m'
'INFO-: create.result: 1 started because log is /Users/marcel/oosh/log
  this -> this: create.result:180   - this this log log log '[' '' = save ']'
  this -> this: create.result:186   - this this log log log info.log 'next argument: '
  this -> this: info.log:34   - this this this log log log '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this this log log log echo -e '\e[90mINFO-: next argument: \e[0m'
'INFO-: next argument: 
  this -> log: this.isSourced:509   - this log log log result
  this -> this: result:194   - this this log log log '[' '' = save ']'
  this -> this: result:199   - this this log log log '[' -z 1 ']'
  this -> this: result:202   - this this log log log echo 1
  this -> log: this.isSourced:509   - this log log log info.log 'return result 1'
  this -> this: info.log:34   - this this log log log '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this log log log echo -e '\e[90mINFO-: return result 1\e[0m'
'INFO-: return result 1
  this -> log: this.isSourced:510   - this log log log result
  this -> this: result:194   - this this log log log '[' '' = save ']'
  this -> this: result:199   - this this log log log '[' -z 1 ']'
  this -> this: result:202   - this this log log log echo 1
  this -> log: this.isSourced:510   - this log log log return 1
  log -> log: log.level:247   - log log log info.log 'log level started'
  this -> log: info.log:34   - this log log log '[' 6 -gt 3 ']'
  this -> log: info.log:35   - this log log log echo -e '\e[90mINFO-: log level started\e[0m'
'INFO-: log level started
  log -> log: log.level:248   - log log log config save log LOG
'INFO-: this.load does not exist
  debug -> debug: setTrap:276   - debug debug this config config onReturn 0
'- function setTrap returned with code: 0 and  RESULT=
  this -> config: source:114   - this config config step
  this -> config: source:114   - this config config onReturn 0
'- function source returned with code: 0 and  RESULT=
  this -> config: source:620   - this config config step
  this -> config: source:620   - this config config info.log '
'still in this
''
  this -> this: info.log:34   - this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this config config echo -e '\e[90mINFO-: 
'still in this
'\e[0m'
'INFO-: 
'still in this

  this -> config: source:623   - this config config step
  this -> config: source:623   - this config config this.init
  this -> this: this.init:118   - this this config config info.log inititlized
  this -> this: info.log:34   - this this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this this config config echo -e '\e[90mINFO-: inititlized\e[0m'
'INFO-: inititlized
  this -> this: this.init:121   - this this config config dirname /Users/marcel/oosh/this
  this -> this: this.init:121   - this this config config local initStartPath=/Users/marcel/oosh
  this -> this: this.init:122   - this this config config let shellLevel=5-1
  this -> this: this.init:123   - this this config config let ooShellLevel=5+2
  this -> this: this.init:132   - this this config config '[' config = config ']'
  this -> this: this.init:142   - this this config config '[' -z 'oosh ' ']'
  this -> config: source:627   - this config config case "${0##*/}" in
  this -> config: source:627   - this config config step
  this -> config: source:645   - this config config step
  this -> config: source:645   - this config config info.log '  running config'
  this -> this: info.log:34   - this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this config config echo -e '\e[90mINFO-:   running config\e[0m'
'INFO-:   running config
  this -> config: source:656   - this config config this.isSourced
  this -> this: this.isSourced:485   - this this config config caller=this
  this -> this: this.isSourced:486   - this this config config callerFunction=source
  this -> this: this.isSourced:488   - this this config config case $callerFunction in
  this -> this: this.isSourced:503   - this this config config '[' config = this ']'
  this -> this: this.isSourced:506   - this this config config create.result 0 'sourced because called by source in this'
  this -> this: create.result:167   - this this this config config RETURN_VALUE=0
  this -> this: create.result:168   - this this this config config shift
  this -> this: create.result:169   - this this this config config RESULT='sourced because called by source in this'
  this -> this: create.result:170   - this this this config config shift
  this -> this: create.result:171   - this this this config config RETURN=
  this -> this: create.result:174   - this this this config config this.isNumber 0
  this -> this: this.isNumber:40   - this this this this config config case $1 in
  this -> this: this.isNumber:42   - this this this this config config return 0
  this -> this: create.result:179   - this this this config config info.log 'create.result: 0 sourced because called by source in this'
  this -> this: info.log:34   - this this this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this this this config config echo -e '\e[90mINFO-: create.result: 0 sourced because called by source in this\e[0m'
'INFO-: create.result: 0 sourced because called by source in this
  this -> this: create.result:180   - this this this config config '[' '' = save ']'
  this -> this: create.result:186   - this this this config config info.log 'next argument: '
  this -> this: info.log:34   - this this this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this this this config config echo -e '\e[90mINFO-: next argument: \e[0m'
'INFO-: next argument: 
  this -> this: this.isSourced:509   - this this config config result
  this -> this: result:194   - this this this config config '[' '' = save ']'
  this -> this: result:199   - this this this config config '[' -z 0 ']'
  this -> this: result:202   - this this this config config echo 0
  this -> this: this.isSourced:509   - this this config config info.log 'return result 0'
  this -> this: info.log:34   - this this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this this config config echo -e '\e[90mINFO-: return result 0\e[0m'
'INFO-: return result 0
  this -> this: this.isSourced:510   - this this config config result
  this -> this: result:194   - this this this config config '[' '' = save ']'
  this -> this: result:199   - this this this config config '[' -z 0 ']'
  this -> this: result:202   - this this this config config echo 0
  this -> this: this.isSourced:510   - this this config config return 0
  this -> config: source:657   - this config config step
  this -> config: source:657   - this config config info.log 'this was sourced'
  this -> this: info.log:34   - this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this config config echo -e '\e[90mINFO-: this was sourced\e[0m'
'INFO-: this was sourced
  config -> config: config.start:572   - config config step
  config -> config: config.start:572   - config config onReturn 0
'- function config.start returned with code: 0 and  RESULT=
  config -> config: config.start:575   - config config step
  config -> config: config.start:575   - config config '[' -f /Users/marcel/config/user.env ']'
  config -> config: config.start:583   - config config step
  config -> config: config.start:583   - config config '[' -z /Users/marcel/config ']'
  config -> config: config.start:586   - config config step
  config -> config: config.start:586   - config config type -t this.start
  config -> config: config.start:586   - config config '[' function = function ']'
  config -> config: config.start:587   - config config step
  config -> config: config.start:587   - config config this.start save log LOG
  this -> config: this.start:529   - this config config local len=3
  this -> config: this.start:530   - this config config local caller=config
  this -> config: this.start:531   - this config config local callerFunction=config.start
  this -> config: this.start:533   - this config config which config
  this -> config: this.start:533   - this config config This=/Users/marcel/oosh/config
  this -> config: this.start:534   - this config config this.isSourced
  this -> this: this.isSourced:485   - this this config config caller=this
  this -> this: this.isSourced:486   - this this config config callerFunction=this.start
  this -> this: this.isSourced:488   - this this config config case $callerFunction in
  this -> this: this.isSourced:496   - this this config config '[' main = source ']'
  this -> this: this.isSourced:499   - this this config config create.result 1 'started by  in '
  this -> this: create.result:167   - this this this config config RETURN_VALUE=1
  this -> this: create.result:168   - this this this config config shift
  this -> this: create.result:169   - this this this config config RESULT='started by  in '
  this -> this: create.result:170   - this this this config config shift
  this -> this: create.result:171   - this this this config config RETURN=
  this -> this: create.result:174   - this this this config config this.isNumber 1
  this -> this: this.isNumber:40   - this this this this config config case $1 in
  this -> this: this.isNumber:42   - this this this this config config return 0
  this -> this: create.result:179   - this this this config config info.log 'create.result: 1 started by  in '
  this -> this: info.log:34   - this this this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this this this config config echo -e '\e[90mINFO-: create.result: 1 started by  in \e[0m'
'INFO-: create.result: 1 started by  in 
  this -> this: create.result:180   - this this this config config '[' '' = save ']'
  this -> this: create.result:186   - this this this config config info.log 'next argument: '
  this -> this: info.log:34   - this this this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this this this config config echo -e '\e[90mINFO-: next argument: \e[0m'
'INFO-: next argument: 
  this -> this: this.isSourced:509   - this this config config result
  this -> this: result:194   - this this this config config '[' '' = save ']'
  this -> this: result:199   - this this this config config '[' -z 1 ']'
  this -> this: result:202   - this this this config config echo 1
  this -> this: this.isSourced:509   - this this config config info.log 'return result 1'
  this -> this: info.log:34   - this this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this this config config echo -e '\e[90mINFO-: return result 1\e[0m'
'INFO-: return result 1
  this -> this: this.isSourced:510   - this this config config result
  this -> this: result:194   - this this this config config '[' '' = save ']'
  this -> this: result:199   - this this this config config '[' -z 1 ']'
  this -> this: result:202   - this this this config config echo 1
  this -> this: this.isSourced:510   - this this config config return 1
  this -> config: this.start:540   - this config config '[' -z save ']'
  this -> config: this.start:549   - this config config '[' -n save ']'
  this -> config: this.start:550   - this config config debug.log 'start 1: -save-'
  log -> this: debug.log:131   - log this config config seq.puml.log
  log -> log: seq.puml.log:58   - log log this config config '[' 6 -gt 5 ']'
  log -> log: seq.puml.log:59   - log log this config config export 'PS4=\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:59   - log log this config config PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:60   - log log this config config pumlPrefix='echo ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - '
  log -> log: seq.puml.log:61   - log log this config config export STEP_DEBUG=OFF
  log -> log: seq.puml.log:61   - log log this config config STEP_DEBUG=OFF
  log -> this: debug.log:132   - log this config config '[' 6 -gt 4 ']'
  log -> this: debug.log:133   - log this config config eval echo '${BASH_SOURCE[0]##*/}' '->' '${BASH_SOURCE[1]##*/}:' '${FUNCNAME[0]}:${LINENO}' -
  log -> this: debug.log:133   - log this config config echo log - debug.log:133 -
  log -> this: debug.log:133   - log this config config echo -e '- start 1: -save-'
'- start 1: -save-
  this -> config: this.start:551   - this config config case $1 in
  this -> config: this.start:590   - this config config debug.log 'this.call to: save log LOG'
  log -> this: debug.log:131   - log this config config seq.puml.log
  log -> log: seq.puml.log:58   - log log this config config '[' 6 -gt 5 ']'
  log -> log: seq.puml.log:59   - log log this config config export 'PS4=\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:59   - log log this config config PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:60   - log log this config config pumlPrefix='echo ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - '
  log -> log: seq.puml.log:61   - log log this config config export STEP_DEBUG=OFF
  log -> log: seq.puml.log:61   - log log this config config STEP_DEBUG=OFF
  log -> this: debug.log:132   - log this config config '[' 6 -gt 4 ']'
  log -> this: debug.log:133   - log this config config eval echo '${BASH_SOURCE[0]##*/}' '->' '${BASH_SOURCE[1]##*/}:' '${FUNCNAME[0]}:${LINENO}' -
  log -> this: debug.log:133   - log this config config echo log - debug.log:133 -
  log -> this: debug.log:133   - log this config config echo -e '- this.call to: save log LOG'
'- this.call to: save log LOG
  this -> config: this.start:591   - this config config this.call save log LOG
  this -> this: this.call:340   - this this config config local aFunction=save
  this -> this: this.call:341   - this this config config shift
  this -> this: this.call:343   - this this config config local len=4
  this -> this: this.call:344   - this this config config local caller=config
  this -> this: this.call:346   - this this config config info.log 'script: /Users/marcel/oosh/config'
  this -> this: info.log:34   - this this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this this config config echo -e '\e[90mINFO-: script: /Users/marcel/oosh/config\e[0m'
'INFO-: script: /Users/marcel/oosh/config
  this -> this: this.call:347   - this this config config info.log 'caller: config'
  this -> this: info.log:34   - this this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this this config config echo -e '\e[90mINFO-: caller: config\e[0m'
'INFO-: caller: config
  this -> this: this.call:349   - this this config config this.functionExists save
'INFO-: save does not exist
  this -> this: this.call:356   - this this config config this.functionExists config.save
'INFO-: config.save exists
  this -> this: this.call:357   - this this config config debug.log 'this.call: config.save log LOG'
  log -> this: debug.log:131   - log this this config config seq.puml.log
  log -> log: seq.puml.log:58   - log log this this config config '[' 6 -gt 5 ']'
  log -> log: seq.puml.log:59   - log log this this config config export 'PS4=\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:59   - log log this this config config PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:60   - log log this this config config pumlPrefix='echo ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - '
  log -> log: seq.puml.log:61   - log log this this config config export STEP_DEBUG=OFF
  log -> log: seq.puml.log:61   - log log this this config config STEP_DEBUG=OFF
  log -> this: debug.log:132   - log this this config config '[' 6 -gt 4 ']'
  log -> this: debug.log:133   - log this this config config eval echo '${BASH_SOURCE[0]##*/}' '->' '${BASH_SOURCE[1]##*/}:' '${FUNCNAME[0]}:${LINENO}' -
  log -> this: debug.log:133   - log this this config config echo log - debug.log:133 -
  log -> this: debug.log:133   - log this this config config echo -e '- this.call: config.save log LOG'
'- this.call: config.save log LOG
  this -> this: this.call:358   - this this config config config.save log LOG
  config -> this: config.save:270   - config this this config config local file=log
  config -> this: config.save:271   - config this this config config shift
  config -> this: config.save:272   - config this this config config local name=LOG
  config -> this: config.save:273   - config this this config config '[' -z LOG ']'
  config -> this: config.save:276   - config this this config config shift
  config -> this: config.save:280   - config this this config config '[' -n log ']'
  config -> this: config.save:281   - config this this config config config.file log.env
  config -> config: config.file:409   - config config this this config config '[' -z log.env ']'
  config -> config: config.file:412   - config config this this config config case "$1" in
  config -> config: config.file:421   - config config this this config config export FILE=log.env
  config -> config: config.file:421   - config config this this config config FILE=log.env
  config -> config: config.file:422   - config config this this config config CONFIG_FILE=log.env
  config -> config: config.file:424   - config config this this config config export CONFIG=/Users/marcel/config/log.env
  config -> config: config.file:424   - config config this this config config CONFIG=/Users/marcel/config/log.env
  config -> this: config.save:287   - config this this config config info.log '
'config.save  to /Users/marcel/config/log.env'
  this -> config: info.log:34   - this config this this config config '[' 6 -gt 3 ']'
  this -> config: info.log:35   - this config this this config config echo -e '\e[90mINFO-: 
'  config.save  to /Users/marcel/config/log.env\e[0m'
'INFO-: 
'  config.save  to /Users/marcel/config/log.env
  config -> this: config.save:290   - config this this config config RESULT=
  config -> this: config.save:293   - config this this config config declare -p
  config -> this: config.save:293   - config this this config config grep '^\(declare -[^aA]* \)*\([^ ]*LOG\)\(.*\)='
  config -> this: config.save:293   - config this this config config sed 's/^\(declare -.* \)\(.*LOG\)\(.*\)=\(.*\)/export \2\3=\4/'
  config -> this: config.save:296   - config this this config config '[' -z log ']'
  config -> this: config.save:312   - config this this config config config.info.log
  config -> config: config.info.log:339   - config config this this config config '[' 6 -gt 3 ']'
  config -> config: config.info.log:340   - config config this this config config config.list
  config -> config: config.list:321   - config config config this this config config config.check.file
  config -> config: config.check.file:392   - config config config config this this config config '[' -n '' ']'
  config -> config: config.check.file:398   - config config config config this this config config RETURN_VALUE=1
  config -> config: config.check.file:400   - config config config config this this config config info.log 'config file: /Users/marcel/config/log.env'
  this -> config: info.log:34   - this config config config config this this config config '[' 6 -gt 3 ']'
  this -> config: info.log:35   - this config config config config this this config config echo -e '\e[90mINFO-: config file: /Users/marcel/config/log.env\e[0m'
'INFO-: config file: /Users/marcel/config/log.env
  config -> config: config.check.file:401   - config config config config this this config config create.result 1 /Users/marcel/config/log.env
  this -> config: create.result:167   - this config config config config this this config config RETURN_VALUE=1
  this -> config: create.result:168   - this config config config config this this config config shift
  this -> config: create.result:169   - this config config config config this this config config RESULT=/Users/marcel/config/log.env
  this -> config: create.result:170   - this config config config config this this config config shift
  this -> config: create.result:171   - this config config config config this this config config RETURN=
  this -> config: create.result:174   - this config config config config this this config config this.isNumber 1
  this -> this: this.isNumber:40   - this this config config config config this this config config case $1 in
  this -> this: this.isNumber:42   - this this config config config config this this config config return 0
  this -> config: create.result:179   - this config config config config this this config config info.log 'create.result: 1 /Users/marcel/config/log.env'
  this -> this: info.log:34   - this this config config config config this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this config config config config this this config config echo -e '\e[90mINFO-: create.result: 1 /Users/marcel/config/log.env\e[0m'
'INFO-: create.result: 1 /Users/marcel/config/log.env
  this -> config: create.result:180   - this config config config config this this config config '[' '' = save ']'
  this -> config: create.result:186   - this config config config config this this config config info.log 'next argument: '
  this -> this: info.log:34   - this this config config config config this this config config '[' 6 -gt 3 ']'
  this -> this: info.log:35   - this this config config config config this this config config echo -e '\e[90mINFO-: next argument: \e[0m'
'INFO-: next argument: 
  config -> config: config.check.file:402   - config config config config this this config config result
  this -> config: result:194   - this config config config config this this config config '[' '' = save ']'
  this -> config: result:199   - this config config config config this this config config '[' -z 1 ']'
  this -> config: result:202   - this config config config config this this config config echo 1
  config -> config: config.check.file:402   - config config config config this this config config return 1
  config -> config: config.list:322   - config config config this this config config cat /Users/marcel/config/log.env
'export LOGNAME="marcel"
'export LOG_DEVICE="/dev/tty"
'export LOG_LEVEL="6"
'export LOG_LEVEL_RESET="3"
  this -> config: this.start:595   - this config config shift
  this -> config: this.start:597   - this config config '[' '!' '' = log ']'
  this -> config: this.start:598   - this config config shift
  this -> config: this.start:599   - this config config debug.log 'shift:  -Return:-  -LOG- -command=save log LOG-  =LOG='
  log -> this: debug.log:131   - log this config config seq.puml.log
  log -> log: seq.puml.log:58   - log log this config config '[' 6 -gt 5 ']'
  log -> log: seq.puml.log:59   - log log this config config export 'PS4=\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:59   - log log this config config PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:60   - log log this config config pumlPrefix='echo ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - '
  log -> log: seq.puml.log:61   - log log this config config export STEP_DEBUG=OFF
  log -> log: seq.puml.log:61   - log log this config config STEP_DEBUG=OFF
  log -> this: debug.log:132   - log this config config '[' 6 -gt 4 ']'
  log -> this: debug.log:133   - log this config config eval echo '${BASH_SOURCE[0]##*/}' '->' '${BASH_SOURCE[1]##*/}:' '${FUNCNAME[0]}:${LINENO}' -
  log -> this: debug.log:133   - log this config config echo log - debug.log:133 -
  log -> this: debug.log:133   - log this config config echo -e '- shift:  -Return:-  -LOG- -command=save log LOG-  =LOG='
'- shift:  -Return:-  -LOG- -command=save log LOG-  =LOG=
  this -> config: this.start:600   - this config config '[' -z LOG ']'
  this -> config: this.start:597   - this config config '[' '!' '' = LOG ']'
  this -> config: this.start:598   - this config config shift
  this -> config: this.start:599   - this config config debug.log 'shift:  -Return:-  -- -command=save log LOG-  =='
  log -> this: debug.log:131   - log this config config seq.puml.log
  log -> log: seq.puml.log:58   - log log this config config '[' 6 -gt 5 ']'
  log -> log: seq.puml.log:59   - log log this config config export 'PS4=\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:59   - log log this config config PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:60   - log log this config config pumlPrefix='echo ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - '
  log -> log: seq.puml.log:61   - log log this config config export STEP_DEBUG=OFF
  log -> log: seq.puml.log:61   - log log this config config STEP_DEBUG=OFF
  log -> this: debug.log:132   - log this config config '[' 6 -gt 4 ']'
  log -> this: debug.log:133   - log this config config eval echo '${BASH_SOURCE[0]##*/}' '->' '${BASH_SOURCE[1]##*/}:' '${FUNCNAME[0]}:${LINENO}' -
  log -> this: debug.log:133   - log this config config echo log - debug.log:133 -
  log -> this: debug.log:133   - log this config config echo -e '- shift:  -Return:-  -- -command=save log LOG-  =='
'- shift:  -Return:-  -- -command=save log LOG-  ==
  this -> config: this.start:600   - this config config '[' -z '' ']'
  this -> config: this.start:601   - this config config debug.log 'force stop'
  log -> this: debug.log:131   - log this config config seq.puml.log
  log -> log: seq.puml.log:58   - log log this config config '[' 6 -gt 5 ']'
  log -> log: seq.puml.log:59   - log log this config config export 'PS4=\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:59   - log log this config config PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:60   - log log this config config pumlPrefix='echo ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - '
  log -> log: seq.puml.log:61   - log log this config config export STEP_DEBUG=OFF
  log -> log: seq.puml.log:61   - log log this config config STEP_DEBUG=OFF
  log -> this: debug.log:132   - log this config config '[' 6 -gt 4 ']'
  log -> this: debug.log:133   - log this config config eval echo '${BASH_SOURCE[0]##*/}' '->' '${BASH_SOURCE[1]##*/}:' '${FUNCNAME[0]}:${LINENO}' -
  log -> this: debug.log:133   - log this config config echo log - debug.log:133 -
  log -> this: debug.log:133   - log this config config echo -e '- force stop'
'- force stop
  this -> config: this.start:602   - this config config RETURN=
  this -> config: this.start:603   - this config config exit 1
  this -> config: this.start:1   - this config config onExit 1
  debug -> this: onExit:272   - debug this config config debug.log exiting
  log -> debug: debug.log:131   - log debug this config config seq.puml.log
  log -> log: seq.puml.log:58   - log log debug this config config '[' 6 -gt 5 ']'
  log -> log: seq.puml.log:59   - log log debug this config config export 'PS4=\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:59   - log log debug this config config PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:60   - log log debug this config config pumlPrefix='echo ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - '
  log -> log: seq.puml.log:61   - log log debug this config config export STEP_DEBUG=OFF
  log -> log: seq.puml.log:61   - log log debug this config config STEP_DEBUG=OFF
  log -> debug: debug.log:132   - log debug this config config '[' 6 -gt 4 ']'
  log -> debug: debug.log:133   - log debug this config config eval echo '${BASH_SOURCE[0]##*/}' '->' '${BASH_SOURCE[1]##*/}:' '${FUNCNAME[0]}:${LINENO}' -
  log -> debug: debug.log:133   - log debug this config config echo log - debug.log:133 -
  log -> debug: debug.log:133   - log debug this config config echo -e '- exiting'
'- exiting
  log -> log: log.level:249   - log log log exit 0
  log -> log: log.level:1   - log log log onExit 0
  debug -> log: onExit:272   - debug log log log debug.log exiting
  log -> debug: debug.log:131   - log debug log log log seq.puml.log
  log -> log: seq.puml.log:58   - log log debug log log log '[' 6 -gt 5 ']'
  log -> log: seq.puml.log:59   - log log debug log log log export 'PS4=\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:59   - log log debug log log log PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
  log -> log: seq.puml.log:60   - log log debug log log log pumlPrefix='echo ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - '
  log -> log: seq.puml.log:61   - log log debug log log log export STEP_DEBUG=OFF
  log -> log: seq.puml.log:61   - log log debug log log log STEP_DEBUG=OFF
  log -> debug: debug.log:132   - log debug log log log '[' 6 -gt 4 ']'
  log -> debug: debug.log:133   - log debug log log log eval echo '${BASH_SOURCE[0]##*/}' '->' '${BASH_SOURCE[1]##*/}:' '${FUNCNAME[0]}:${LINENO}' -
  log -> debug: debug.log:133   - log debug log log log echo log - debug.log:133 -
  log -> debug: debug.log:133   - log debug log log log echo -e '- exiting'
'- exiting
@enduml