#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: 
	$0 alias 
	"
    exit 0
fi

target=$(alisma -p "$1")
echo "$target"
if [ ! -L "$1.link" ]; then
    ln -s "$target" "$1.link"
else
    echo "$1.link   already exists."
    ls -alhF "$1.link"
fi




### fins all aliasses
# mdfind kMDItemKind="Alias"
