name: macOS Install Test
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: true
        default: 'dev'

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install oosh as user
        run: |
          export OOSH_INSTALL_SOURCE="$GITHUB_WORKSPACE"
          bash init/oosh
          echo "$HOME/oosh" >> $GITHUB_PATH

      - name: Run tests as user
        shell: /opt/homebrew/bin/bash -e {0}
        run: |
          source "$HOME/config/user.env" 2>/dev/null || true
          test.suite core 1

      - name: Install oosh as root
        run: |
          sudo -H OOSH_INSTALL_SOURCE="$GITHUB_WORKSPACE" bash init/oosh

      - name: Run tests as root
        shell: /opt/homebrew/bin/bash -e {0}
        run: |
          sudo -H /opt/homebrew/bin/bash -c '
            source /var/root/config/user.env 2>/dev/null || true
            export PATH="/var/root/oosh:$PATH"
            test.suite core 1
          '
